/*
 * File: app/view/PayerPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PayerPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.payerPanelAlias',

    config: {
        centered: true,
        hidden: true,
        id: 'payerPanel',
        itemId: 'payerPanel',
        styleHtmlContent: true,
        hideOnMaskTap: true,
        modal: true,
        scrollable: 'vertical',
        cls: [
            'modalPanel'
        ],
        hideAnimation: {
            type: 'popOut',
            duration: 250,
            easing: 'ease-in'
        },
        showAnimation: {
            type: 'popIn',
            duration: 250,
            easing: 'ease-out'
        },
        tpl: [
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '<div class="x-input-el value">Just one step to get money</div>',
            '</div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '    <div class="x-form-label label">',
            '        <span>Name</span>',
            '    </div>',
            '    <div class="x-input-el value">',
            '        <span>{name} {lastname}</span>',
            '    </div>',
            '</div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '    <div class="x-form-label label">',
            '        <span>Concept</span>',
            '    </div>',
            '    <div class="x-input-el value">',
            '        <span>Commerce\'s Shake and Pay</span>',
            '    </div>',
            '</div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">        ',
            '    <div class="x-form-label label myLabel">',
            '        <span>Amount</span>',
            '    </div>',
            '    <div class="x-input-el value">',
            '        <span>{amount} €</span>',
            '    </div>',
            '</div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '    <div class="x-form-label label">',
            '        <span>Press Ok to execute {name}\'s payment</span>',
            '    </div>',
            '<div>'
        ],
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Payer found'
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: '100px',
                defaults: {
                    flex: 1
                },
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'actionButton',
                        id: 'payerCancelButton',
                        itemId: 'payerCancelButton',
                        ui: 'decline',
                        text: 'No'
                    },
                    {
                        xtype: 'button',
                        cls: 'actionButton',
                        id: 'payerOkButton',
                        itemId: 'payerOkButton',
                        ui: 'confirm',
                        text: 'Yes'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onPayerCancelButtonTap',
                event: 'tap',
                delegate: '#payerCancelButton'
            },
            {
                fn: 'onPayerOkButtonTap',
                event: 'tap',
                delegate: '#payerOkButton'
            }
        ]
    },

    onPayerCancelButtonTap: function(button, e, options) {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: ' Cancelling operation '
        });

        setTimeout(function(){    
            Ext.Viewport.setMasked(false);
            Ext.getCmp('payerPanel').hide();                
        },1000);
    },

    onPayerOkButtonTap: function(button, e, options) {
        var me = this;
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: ' Getting Token '
        });

        // simulate event
        setTimeout(function(){    
            Ext.Viewport.setMasked(false);
            var me = this;
            Ext.Viewport.setMasked({
                xtype: 'loadmask',
                message: ' Making the payment '
            });

            setTimeout(function(){    
                Ext.Viewport.setMasked(false);
                Ext.Msg.alert('Success', 'Payment Done!');
                Ext.getCmp('payerPanel').hide();                
            },3000);

        },3000);

    },

    getView: function(viewId) {

        var view = Ext.getCmp(viewId);
        if (view === undefined) {
            view = Ext.widget(viewId+'Alias');
        }
        return view;

    }

});