/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
    },

    getView: function(viewId) {

        var view = Ext.getCmp(viewId);
        if (view === undefined) {
            view = Ext.widget(viewId+'Alias');
        }
        return view;

    },

    changeView: function(viewId) {

        var destinationView = this.getView(viewId);
        if (destinationView !== undefined) {
            Ext.Viewport.animateActiveItem(destinationView, {
                type: 'fade'
            });
        } else {
            Ext.Logger.error("No existe la vista de destino");
        }



    }

});